name: SillOS CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get install \
            nasm \
            xorriso \
            qemu-system-x86

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: x86_64-unknown-none
          components: rustfmt, rust-src

      - name: Build OS
        run: make

  test:
    name: Kernel tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get install \
            nasm \
            xorriso \
            qemu-system-x86

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: x86_64-unknown-none
          components: rust-src

      - name: Run kernel tests
        run: make test

  release:
    name: Release ISO
    needs:
      - build
      - test
    if: github.event_name == 'push' && github.ref_type == 'tag'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get install \
            nasm \
            xorriso

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: x86_64-unknown-none
          components: rust-src

      - name: Build ISO
        run: make

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: sillos.iso
          generate_release_notes: true
